version: '3.8'
services:
  ecommerce:
    container_name: ecommerce
    restart: always
    build: './ecommerce-flask-stripe'
    networks:
      - load-balancer
networks:
  server_load_balancer:
    external: true